# Generated by Django 3.0.3 on 2020-02-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo_url',
            field=models.ImageField(upload_to='actors_photos/'),
        ),
    ]
