# Generated by Django 3.0.3 on 2020-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorite',
        ),
        migrations.AddField(
            model_name='watched',
            name='favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
